/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [
	//   {type: 'autogenerated', dirName: 'tutorial-basics/easy', },
	//   {type: 'autogenerated', dirName: 'tutorial-basics/mid'},
	// ],

	// But you can create a sidebar manually

	// tutorialSidebar: [
	//   {
	//     type: 'category',
	//     label: 'Tutorial',
	//     items: ['tutorial-basics/create-a-document'],
	//   },
	//   {
	//     type: 'category',
	//     label: 'twoSider',
	//     items: ['tutorial-extras/translate-your-site'],
	//   },
	// ],
	frontSidebar: [
		"FrontEnd/intro",
		{
			type: "category",
			label: "HTML5/CSS3基础",
			items: [{ type: "autogenerated", dirName: "FrontEnd/H5C3" }],
		},
		{
			type: "category",
			label: "JS基础",
			items: [{ type: "autogenerated", dirName: "FrontEnd/JS-Weak" }],
		},
		{
			type: "category",
			label: "JS进阶",
			items: [{ type: "autogenerated", dirName: "FrontEnd/JS-Strong" }],
		},
		{
			type: "category",
			label: "Node基础",
			items: [
				{
					type: "category",
					label: "网络通信",
					items: [
						{
							type: "autogenerated",
							dirName: "FrontEnd/Node-Weak/NetCommunicate",
						},
					],
				},
				{
					type: "category",
					label: "Node服务端基础",
					items: [
						{ type: "autogenerated", dirName: "FrontEnd/Node-Weak/Node_base" },
					],
				},
			],
		},
		{
			type: "category",
			label: "前端工程化准备",
			items: [{ type: "autogenerated", dirName: "FrontEnd/Prj-Pre" }],
		},
		{
			type: "category",
			label: "React框架",
			items: [{ type: "autogenerated", dirName: "FrontEnd/react" }],
		},
		{
			type: "category",
			label: "Vue框架",
			items: [{ type: "autogenerated", dirName: "FrontEnd/vue" }],
		},
		{
			type: "category",
			label: "服务端渲染",
			items: [{ type: "autogenerated", dirName: "FrontEnd/SSR" }],
		},
		{
			type: "category",
			label: "大前端开发",
			items: [
				{
					type: "category",
					label: "服务端方向",
					items: [
						{
							type: "autogenerated",
							dirName: "FrontEnd/FrontEnd-Wider/server",
						},
					],
				},
				{
					type: "category",
					label: "小程序方向",
					items: [
						{
							type: "autogenerated",
							dirName: "FrontEnd/FrontEnd-Wider/mini_app",
						},
					],
				},
				{
					type: "category",
					label: "移动端方向",
					items: [
						{
							type: "autogenerated",
							dirName: "FrontEnd/FrontEnd-Wider/mobile",
						},
					],
				},
			],
		},
	],

	schoolSidebar: [
		"school/intro",
		{
			type: "category",
			label: "大学物理",
			items: [{ type: "autogenerated", dirName: "school/physics" }],
		},
		{
			type: "category",
			label: "数据库",
			items: [{ type: "autogenerated", dirName: "school/dataBase" }],
		},
		{
			type: "category",
			label: "数电-模电",
			items: [{ type: "autogenerated", dirName: "school/circuit" }],
		},
		{
			type: "category",
			label: "政治课程",
			items: [{ type: "autogenerated", dirName: "school/politics" }],
		},
		{
			type: "category",
			label: "计算机网络",
			items: [{ type: "autogenerated", dirName: "school/csNet" }],
		},
		{
			type: "category",
			label: "JAVA程序设计",
			items: [{ type: "autogenerated", dirName: "school/java" }],
		},
		{
			type: "category",
			label: "操作系统",
			items: [{ type: "autogenerated", dirName: "school/osSystem" }],
		},
		{
			type: "category",
			label: "Linux专题",
			items: [{ type: "autogenerated", dirName: "school/Linux" }],
		},
	],
	techSidebar: [
		"Tech/intro",
		{
			type: "category",
			label: "Golong 后端开发",
			items: [{ type: "autogenerated", dirName: "Tech/golong_server" }],
		},
		{
			type: "category",
			label: "Node.js后端开发",
			items: [{ type: "autogenerated", dirName: "Tech/node" }],
		},
		{
			type: "category",
			label: "Python后端开发",
			items: [{ type: "autogenerated", dirName: "Tech/python_server" }],
		},
	],
};

module.exports = sidebars;
